* 关于火狐
  火狐的前身是盛极一时的 ~Netscape~ ，MS利用随系统捆绑发布的卑鄙手法推广 ~IE~ ，最终 ~IE~ 战胜了 ~Netscape~  ，直到现在 ~IE~ 还是这样推广的。虽然对 ~MS~ 的官司网景获胜，但那是很久以后的事了， ~IE~ 已经占领市场。为了再度占领市场网景将代码大部分开源，成立 ~Mozilla.org~ 组织，于是有了火狐。对于 ~Windows~ 系统的用户，尤其是普通用户，基本上用的都是基于 ~IE~ 内核的浏览器，但 ~IE~ 是绝对不会开发其他平台上的版本的，所以在 ~Linux~ 上火狐就成了正宗。由于火狐的开源，像其他大型开源软件一样，有自己的社区，和一批忠实的爱好者和自由开发者，由于这些人具有一定的开发能力，他们希望世界按自己的方式运转，因此火狐有更好的定制性和灵活性，能实现各种各样的功能。又由于这些人多是懒蛋，多一个按键他们都不想按，所以火狐可以高效地使用。
* 外观
** 主题
   首先是主题的问题。如果在 ~win7~ 上安装一个苹果风格的软件， ~windows~ 系统的毛玻璃效果加上苹果的质感肯定很不协调。暴风影音似乎就往这方面发展。所以浏览器主题要跟系统主题相配。火狐官方网站提供了很多主题供选择。
** 布局
   其实火狐的布局并没有多少可以自己定制的余地。在菜单栏右击可以将自己不常用的东西取消掉。选择“Customize” ，通过拖动可以自己选择工具条上的按钮以及它们的位置，当然也可以改变书签工具条的位置。另外 ~Ctr+b~ 和 ~Ctr+h~ 可以在左边分别调出书签栏和历史栏。火狐的定制性基本上就这些。
* 快捷键
  使用快捷键绝对不是为了装X。比如你正在用一个支持全键盘操作的编辑器来编辑文章，要频繁地搜索东西，这时快捷键就很有用，你不用频繁地移动手和目光地找鼠标，思路就不会被打断。再比如你同时打开了25个标签页，要关掉其中的20个。再用鼠标去点击就不是好办法了，只用按住 ~Ctr+w~ 等待两秒钟就行了。
  
  我发现火狐有一个不好的地方就是在不同的平台上一些功能的快捷键是不同的，可能是出于不同用户使用习惯的考虑吧，当然也有可能是避免与其他软件的快捷键冲突。

  下面是 ~Linux~ 上的一些快捷键，当然绝大多数在其他平台上也适用：

 * 常用快捷键

|-----------------+----------------------------------|
| 快捷键          | 功能                             |
|-----------------+----------------------------------|
| ~Ctr+t~         | 打开一个新标签页                 |
| ~Ctr+Shift+t~   | 恢复上一个关闭的标签页           |
| ~Ctr+Tab~       | 切换到下一个标签页               |
| ~Ctr+Shift+Tab~ | 切换到上一个标签页               |
| ~Ctr+w~         | 关闭当前标签页                   |
| ~Ctr+Shift+w~   | 关闭火狐（打开多个标签页时询问） |
| ~Ctr+l~         | 地址栏聚焦                       |
| ~Ctr+j~         | 搜索栏聚焦                       |
|-----------------+----------------------------------|
\\
 * 不常用快捷键

|---------------+--------------------------------------|
| 快捷键        | 功能                                 |
|---------------+--------------------------------------|
| ~Ctr+q~       | 直接关闭火狐                         |
| ~Ctr+f~       | 查找                                 |
| ~Ctr+d~       | 将当前页面保存成书签（会弹出对话框） |
| ~Ctr+o~       | 打开文件                             |
| ~Ctr+s~       | 保存当前页                           |
| ~Ctr+b~       | 打开/关闭书签栏                      |
| ~Ctr+h~       | 打开/关闭历史栏                      |
| ~Ctr+p~       | 打印当前页                           |
| ~Ctr+z~       | 撤消操作                             |
| ~Ctr+Shift+z~ | 重做                                 |
|---------------+--------------------------------------|

* 手势操作
  所谓手势操作,就是通过右击画出不同的轨迹来执行不同的操作。这个实在是太好用了，因为随意地画一个轨迹要比小心翼翼地去点击一个按钮轻松得多，于是不得不说下。

  这个功能首先是在搜狗浏览器上见到的，可惜搜狗似乎不怎么宣传，很多一直使用这个浏览器的同学也不知道有这么个功能。然后就找火狐上的插件，果然有相应的插件——FireGesture。这个插件似乎是个日本人写的，它具有很强的定制性，可以支持自定义手势，轨迹线条粗度，轨迹颜色等。还可以跟控制键配合使用，这样你就可以根据自己的习惯进行设置。值得提下，开始使用时总是感觉没有搜狗的好用，后来发现是因为它默认设置的轨迹线条很细，设置粗一点儿看着更舒服些。另外它是基于脚本的，每个功能都是用一个脚本实现的，你可以到网上去找更多的脚本，或者自己写脚本，这样它几乎就可以实现所有你想要的功能。至于怎样安装这个插件见下面。
* 插件
  使用 ~IE~ 的人基本上不会有这个概念。浏览器插件就是在浏览器提供的接口的基础上进一步开发的扩展软件。由于火狐是开源的软件，所以有更多的开源爱好者支持，而他们又多是程序猿， ~Mozilla~ 官方又提供了插件共享平台，这样火狐的插件就特别多。它们的作者不是靠软件收费生存，也没有可恶的广告，他们多是出于自己的兴趣，靠捐助维持项目。

  至于安装很简单，可以到[[https://addons.mozilla.org/en-US/firefox/][官方网站]]去找插件，也可以 ~Ctr+Shift+A~ ，然后在插件处理器中搜索安装。
** FireGestures
   已经说过。这个是一定要安装的。
** Adblock Plus
   广告满天飞的世界里，这个也是必需的。当然安装之后要订阅广告过滤列表，它的原理是充分发动群众，建立反对广告的统一战线，大家都把自己发现的广告共享，再多的广告我们也能都给它过滤掉。

   它不仅可以过滤图片也可以过滤帧，对于广告最好使用过滤帧，因为过滤图片会留下空白。

   如果发现有广告没过滤掉，右击选择 ~Adblock~ 给它过滤掉。
** Ease Link
   这个插件就有点邪恶了。它能解析迅雷、快车、RayFile、纳米盘、QQ旋风等链接，并且也能够解析纯文本形式的链接并将它转换成超链接。这样就可以用其它下载软件直接下载了。很明显这是国人开发的。作者还推荐与 ~FlashGot~ 一同使用，真无耻。
** NetVideoHunter
   这个插件也特别有用，当你看到好的视频时总想保存下来吧。记得以前还能在本地缓存中找到相应的视频文件，后来火狐好像是为了安全，不在本地直接保存图片、视频等文件了。另外国内一些视频网站也极力不想让用户得到视频，这时这个插件就是必要的了。每打开一个网页它会自动解析视频文件。你可以用它直接播放或者下载到本地。我不知道这个软件是怎么做的，但我还没有发现国内的哪个视频网站的视频是它下载不了的。
** Speed Dial
   好像是 ~Opera~ 默认有这么个东西，当一个首页不能满足你时，可以用这个插件，将百度、谷歌、雅虎、新浪神马的都放到首页去吧。它的选项也很丰富，还支持快捷键。比如默认情况下你用 ~Ctr+1~ 就可以打开第一个地址， ~Ctr+n~ 就可以打开第n个地址。当然这些快捷键可以自己修改。
** AutoProxy
   不解释。但提醒下，它也有自己的类似于 ~Adblock Plus~ 的订阅列表，认清国情，别选错了。
** Easy DragToGo
   之所以用它只是为了保存图片。其实 ~FireGestures~ 也可以实现保存图片的功能，但每次都让你选择路径，一两个图片还可以，如果是几十个就受不了了。它也支持自定义手势，比如我的设置是，点击图片往左拖一下，可以在新的标签页中打开这个图片，点击图片往右拖，自动保存，不用你来指定位置。它很不错的一点是当你指定一个根文件夹后，它在里面根据网址建立不同的文件夹，将同一网址的图片放在同一文件夹内。它还有几个其他功能，总的来说这个插件还是比较简单小巧的。

   它与 FireGestures 有所不同， ~FireGestures~ 是从鼠标按下开始计算轨迹，当轨迹不合法时不执行任何动作，一般你执行一个动作后又后悔了，就可以随便晃动下，造成一个非法动作就行了。但这个插件不是这样，不管你的轨迹是什么，只要最后一刻你的鼠标是往左的，它都会打开它。
** Mouseless Browsing
   这个插件是给纯键盘控用的。这些人不满足于 ~lynx~ 、 ~w3m~ 等终端浏览器的丑陋界面，又苦于火狐没有快速地移动定位光标的快捷键，于是发明并使用这个东西。其实这个插件学习起来很简单，远远不及 ~lynx~ 和 ~w3m~ 的命令难记，因为它只是负责打开链接。它给每个链接加一个数字，直接敲击这个数字就可以打开链接。配合火狐的快捷键，基本上能赶上终端浏览器的操作效率。缺点是网页加上数字之后就有点儿乱。
** Read It Later
   将你现在没有时间读的网页保存起来有空时再读。它的功能有点多，多到我看了好长时间都不知道到底是怎么使用的。反正我基本上没用过它，我都是将这样的网页直接 ~Ctr+d~ 加个“未读完”标记，放在书签里。
** Tab Utilities
   这个插件使你可以决定在不同的动作下标签页的行为。记得搜狗之类的浏览器可以双击标签页关闭当前标签，双击标签栏空白处可以新建标签页，而火狐3时好像还没有这些功能，就安装了这个插件，现在火狐9都出来了，不知道改进了否。反正它对我来说最有用的功能就是当我在地址栏里直接输入地址或者点击书签工具条上的书签时，打开网页会新建一个标签页，而不是傻傻地将当前页覆盖掉。这样就可以少按一个 ~Ctr+t~ 。
** FlashGot
   下载东西的，不是有个无耻的作者推荐过了么。还有一个下载管理器可以支持断点续传，叫 ~DownThemAll~ ，界面很美观。这两个插件我都不怎么用。
** ScribeFire
   可以想像当你用一些网站提供的在线博客编辑器写一篇一万字的博客时，当你敲入九千九百九十九个字时，停电了，你会是什么感受。用 ~ScribeFire~ 吧，它现在已经基本上支持所有博客平台，可以很方便地管理多个博客，可以将文章保存在本地，可以保存草稿，可以在浏览网页时直接保存素材，而且支持 ~html~ 编辑，总之方便而且很安全。当然这都是以前的使用感受了，现在又出新版本了，而且项目也做得很大了，功能肯定更强了。

   其实 ~Windows~ 系统上有很多不错的离线博客软件，如菊子曰等，可以很好地支持国内的博客，只是它们大多要注册，还有广告。对于 ~Linux~ 用户，离线的博客软件倒是有一堆，但几乎没有能很好地支持国内博客的，这时 ~ScribeFire~ 就是一个很好地选择。

   其实还有一个比较好的方法，直接 ~emacs~ + ~Org-mode~ 编辑文章，完成后导出成 ~html~ 文件，利用在线博客的html编辑功能直接发布，既解决了安全性，又解决了编辑过程的高效性。
** CoolPreviews
   这个插件是可以在不打开网页的情况下预览网页。好像还可以保存网页供以后再看，当然还有一些其它功能，没仔细研究过。
** Others
   当然这不是一个插件，我是想说上面这些只是一些对各行各业的用户都通用的插件。其他的不错的插件还有很多，如Rss阅读器（如 ~Sage~ ），音乐电台播放器等。

   当然也有不少专业性的插件，尤其是对软件开发行业的，因为插件开发者本身就是软件开发者。
* 其他
** 书签
*** 分类
    这个很简单，即使用 ~IE~ 的人也知道。就是给不同的书签做不同的标记（ ~tag~ ），方便查找。当你 ~Ctr+d~ 时它会提示你的，当然你也有不做标记的权利。值得一提的是对于经常访问的书签你可以将 “Folder” 一项选成 “Bookmarks Toolbar”，这样就会出现在书签工具条上，点击即可访问。
*** 实时书签
    这个东西在 ~Windows~ 平台的其他浏览器中没注意到，至少没见同学用过。对于可以订阅的网站，尤其是对于一些论坛非常有用。点击rss按钮，对于“Subscribe to this feed using”一项选择“Live Bookmarks”，这样，就会在书签工具条里新建这个网站的订阅书签，当你点击书签时，它不会打开网站，而是显示更新，你可以选择感兴趣的条目查看。每次打开火狐时都会更新这些订阅，当然也可以右击手动更新。
** 切换标签页
   方法很多啦，说一个你可能不知道的。右击不要松开，流动滑轮。
** 获取元素地址
   这是一个很常用的功能，但我发现很多同学都不知道，后来发现IE根本就没有这个功能。点击图片，“Copy Image Location”，点击链接，“Copy Link Location”，即可获得地址。对于迅雷，飞车等的专用链接要想得到直接地址就要与 ~Ease Link~ 配合使用了。

   这个功能有时是很有用的，比如对于 ~verycd~ 上的资源你每次点击一下，它都要你安装电驴，这里你就可以用这个方法跳过这个提示。
** 输入网站地址
   搜狗的方法是直接在地址栏里补全，切换条目时， ~Tab~ 键不能用要去找 ~Up~ 和 ~Down~ 按键，很不方便。火狐的方法要高明得多，当你输入地址时，它会自动弹出下列菜单，根据你输入的内容自动匹配过滤你的访问历史和书签。当你找到想要的网站后可以 ~Tab~ 键或者 ~Shift+Tab~ 进行前后切换选择。当然你不必从开头输入地址，因为这是很慢的。比如我想打开网址 https://bridges.torproject.org 。我只要输入“tor”就可以把它过滤出来，因为其他地址都不包含这个词。所以直接输入地址的方法是很快的。当然如果你从“https”开始输入那就慢多了，不如直接去点击按钮了。
** 复制文本
   有时你可能想将网页上的一些文本复制到一个文本框里，这时你不必 ~Ctr+c~ ， ~Ctr+v~ ，可以选中文本，然后直接拖过去。
** 搜索页面上的文字
   记得搜狗一个很不错的功能是直接选中文本然后在页面上拖动一下再松开，就可以在搜索引擎上查找它了。火狐上拖动文本已作他用了，就没有这个功能，但选中之后右击菜单里会有一个搜索选项，也是很快的，当然也可以拖动文本到右上角的探索栏里，这种操作不常用到，就没找相关插件。
** 打开链接
*** 超链接
    搜狗也可以用拖动超链接再松开的方式打开一个新标签页。火狐可以用手势打开，并且手势可以支持前台打开也可以后台打开。后台打开页面是很有用的，当你浏览一个论坛时，可以同时打开十几个主题，如果是用搜狗，它默认是前台打开，即会跳到新打开的这个页面，每次都要再切换到前一个页面去，很麻烦。用火狐的手势就没有这个问题。


    也可以拖动链接到标签页条上相应位置。当把它拖动到一个标签页上时会覆盖这个页面。顺便说下，标签页的位置是可以移动的，拖动一下就知道了，如果你将它从标签页条上拖动下来，就会新建一个窗口。
*** 纯文本链接
    对于纯文本链接地址，可以选中拖动到标签页条上来打开。
** 地址栏的搜索功能
   其实地址栏里也是可以搜索东西的，当火狐发现你输入的文本不是一个链接时，它就认为是你将 ~Ctr+j~ 错敲成 ~Ctr+l~ 了，于是地址栏就有了搜索栏的功能。
** 打印功能
   不知道 ~Windows~ 版本的有没有这个功能，在 ~Linux~ 上的火狐有一个功能，就是将当前页面保存成 ~pdf~ 格式的， ~Ctr+p~ ，选打印到文件，可以保存在 ~ps~ 或者 ~pdf~ 格式。




#+TITLE:     高效地使用火狐
#+AUTHOR:    Hu Wenbiao
#+EMAIL:     huwenbiao1989@gmail.com
#+DATE:      2011-11-17 四
#+DESCRIPTION: 关于火狐的一些使用经验，给没有用过火狐的人。
#+KEYWORDS: 软件
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   http://www.cnblogs.com/Open_Source/
#+LINK_HOME: http://www.cnblogs.com/Open_Source/
