* 为什么这会是一个问题
  可能你遇到过这种书籍，作者明明是中国人，而书是又是“著”或者“编著”，但里面的句子去诡异得出奇，仿佛一个外国人用生硬的“美式汉语”或“英式汉语”在写作。句式以及用户完全不是中国人的习惯。\\
  可能你也遇到过这种书籍，里面的例子中的变量命名很是怪异，但上下文又完全没有提及，于是你很疑惑作者为什么要举这么一个例子，为什么不能将变量起得通俗一样，那样岂不更好记忆。\\
  当然你可能也会遇到这样的书籍，里面的例子太熟悉了，仿佛几天前你读过的那本名著里的例子，于是找到那本书对比一下，发现有只有两个不同：\\
  1) 那里是C，这里改成了B
  2) 由于上面的改动，反而又引入了一个错误

  正是有了这些书籍的存在，这便是一个问题了，值得仔细研究一下。下面讨论的都是计算机方面的书籍。

  虽然我也也没读过多少书，但不好的书还是遇到过一些。没事时也会想想中国图书市场到底是个什么情况。
* 作者的分类
  学会选书首先应该知道书的作者都是有哪些人。我感觉作者应该有下面几种：
** 大师
  * 出于学术的需要出一些论文，或单独成书或集结成书。这里的学术是真的学术，这里的论文是真的论文。这种人多半在美国，属计算机顶级人物。
  * 也可能是对已知的一些成果的收集。比如Knuth一开始就是想收集一些好的算法，他认为如果这些算法失传就太可惜了。然后这过程中又有了自己的发明创造。
** 领域专家
   某一领域的开创者或者著名专家。比如很多语言的发明者都会有一些名著传世。
** 领军人物
   他们提倡某项东西，就要出书加以推广。
   * 比如开源社区里的鼓吹者将出一些对于开源文化、者哲学，以及对于软件设计的思考这方面的书籍。
   * 再如国内的一些专家，他们将其一领域引入国内，国内当时还没有相关的书籍，他们就要自己写书。
** 高校专家
   由于要讲授某一课程，但当时还没有特别完善的教材，就自己总结讲义，整理成书。
** 学者或者业内人士
   一些多年研究其一领域，或者多年从事某一行业的人，留下大量的笔记和经验，认为于人有益，整理成书，方便他人。
** 某领域狂热者
   在这一领域既非开拓者，也非专家，但是却很狂热，发誓终身为此奋斗。总结经验，自己在网上免费发布一些文章或者电子书籍，读者甚多，好评如潮。出版商联系，希望成书。
** 生活窘迫者
   迫于生活压力，想出书得些补贴。
** 无奈者
   想要评职称，或者获得其他好处，或者迫于其种压力，必须出书，随便找几本类似的书籍，拼凑成书。
** 混蛋（学棍）
   理由同上，但对读者毫不负责，随便找几个下手，让他们搜集资料，整理成书，自己挂名。

* 中文书和外文书的差别
 * 一般来说外文书会比中文书质量好得多，理由如下：
   1) 国外的计算机方面较为先进，国内还处于落后状态。
   2) 国内学术氛围不是很好，更何况近来经济正在快速发展，金钱对人们的影响大过任何其他事物，国人大多难以静下心来做学问。
   3) 看下国内学生作弊的情况就知道国内的图书大概会是个什么样子。
   4) 一本国外的书能被引入国内，至少不会差到哪去。同理，如果是在国外你大可去找国人写的书，如果你能找得到话:)。
 * 一般来说国外的书更贵。这对于国内读者来说是个好消息，因为前句等价于“国内的书更便宜”。
   - 记得曾经有人说国外的书虽然很贵，但老外懂得分享，另外图书馆也多，所以书读起来还是不贵的。
   - 国内的英文版图书大多都是影印版，可能就与版权费太贵有关。
   - 这也说明国外的知识创造更值钱，或者说更被尊重。
   - 另外一般来说翻译的版本比影印版要便宜一些。


  具体地来说，国内的的书基本上都一个样子，定义，证明，例子，最后就是习题，当然最最后还有标准答案。没有时代背景介绍，没有问题的引入，没有原理发现的启发思路，也很少见到启发式习题，更少能在章末指点江山似的讨论谁在这方面取得最优解，谁又将这个最优解作了进一步优化。国人可能”参考“惯了，喜欢总结，喜欢对比，喜欢将定理和性质码得整整齐齐，每一本书都是同一本书，每一位作者都是同一个作者。上了二十多年的学，看了二十多年这种模式的书，你还能再看下去而不吐吗？
  再看国外的书，完全是另外一种风格，每一本书都是不同的人，你能看到作者的学识，看到作者的性格。或许这也是他们的固定模式，我们也应该看看他们的模式，这很好。
  “读一本好书就像跟一个高尚的人谈话”，书是应该有灵气的。
* 结论
  我还发现一个有意思的现象，就是国外的书都是“著“，国内的书只有早期（上世纪70、80年代）的书籍才是”著“，其他的多是”编著“，之所以加个”缟“字，我不知道这是虚心呢，还是心虚呢？
  于是很明显了，选书真的需要“崇洋媚外”。归纳起来就是： *先选国外名著，慎选译著，不选编著* 。下面是总结的一些选书时应该考虑的因素，有些是正面因素，有些是负面的。
* 关于翻译的作品
  翻译向来都是吃力不讨好的事。
  一个好的作品要做到“信、达、雅”，可惜这是文学作品的标准，搞计算机的在文笔方面基本上都不是太好，文学功底不够，能通顺都不错了。更何况很多作者态度有问题，对读者不负责，于是书籍翻译得如机器翻译一般，基本上都是直译，用词、语序完全不是中国人的习惯。就我所读过的译著来说大多生硬，完全不能跟一些文学作品的翻译相比。
  当然也有些作品翻译得不错，尤其是早期的作品。据说《哥德尔 埃舍尔 巴赫——集异璧之大成》这本奇书仅翻译就用了十年，而且不但计算机方面的专家参与其中，还有一些数学专家也参与翻译，另外原书作者虽然不懂中文，也参与了翻译的工作，由此可以想象译著的质量。可见译者的态度问题是最重要的。可惜现在这样的译者就不多见了，当然也可能是沙子太多，将珍珠掩盖了起来，披沙拣金也正是本文的目的。
* 因素
** 正面
*** 作者
    如果你了解这个作者，那么就好办了，我们能知道的人大都是大师或者知名专家，他们的作品绝对是有质量保证的。如果我们不认识呢，用上面的法则吧。另外作者的年龄也可参考，科学家当然是老的更值钱。
*** 年代
    上世纪70、80年代的作品应该是值得信赖的。记得有人说当时（早期贫穷时期）资源匮乏，很多好书不能出版，现在经济好了，很多不该出的书也都出来了。可见那时的书是出版社精心挑选的，另外那里的出版社似乎学术气息要浓于商业气息。
*** 版次
    一本书能一版再版，也从一定程度上说明这不是一本很差劲的书。
*** 参考文献
**** 文献的国别
     如果这是一本计算机方面的图书，后面的参考文献是一片中文，见不到几个字母，那么你基本上可以断定这本书没什么看的价值了。倒不如考虑下后面提供的参考文献。
**** 文献的数目
     我记得《算法导论》的参考文献有320本之多，一个混蛋型的作者绝对不会花这么大的财力、精力去拼凑图书的，因为他花费的代价远大于获得的利益，如果他真的这么干了，那么即使是拼凑出来的东西也值得一读。
**** 文献的形式
     如果文献是放在每一章之后，那么应当给这本书加分。首先能将参考文献放在章节之后，文献的在数量上不会少，另外也说明作者很仔细尽心，想把书写好。如果书中经常看到作者告诉你这个数据是出自谁的哪本书，这个下限是谁在哪里给出的。这本书是值得读的，因为一个混蛋作者是不会费这么大精力给你佛这么详细。另外，当你抄袭别人作业时你会告诉老师这题答案来自谁，那些来自谁吗？显然不会，只有当你完成自己作业时才会标出那个谁谁的答案也很好。
*** 内容形式
    章末注解。这又是一个很有趣的话题。一般国内书籍也会有的，但仅限于对本意作一个概述，而不作其他讨论。当然国外的一些书籍也会作总结，而他们更倾向于告诉你当前本章这个领域是进展情况，以及提供一些你可以进一步获得信息的资源。我个人觉得后者更好一些，因为我个人是不喜欢总结的东西的，太不自然。
*** 读者评论
    人要羞于听取别人的建议。一本好书网上总会好评如潮。大家都认为好的书，即使不好也差不到哪去。
* 从形式上判断
** 从外观上判断一本书
*** 就我的经验，如果一杯书有颜料包装，这本书印刷和纸张质量一般不好，当然特别精美的那种除外，但计算机方面这种精美的书还真没见过。
* 关于出版社
** 关于作者
* 一些我读过的好书
* 一些我知道的好的书系
** 一个好的翻译的例子（有待验证）
   #+begin_example
   #+begin_src 
本书中译本前后费时十余年，译者都是数学和哲学的专家，还得到原作者的直接参与，译文严谨通达，特别是在原作者的帮助下，把西方的文化典故和说法，尽可能转换为中国文化的典故和说法，使这本译本甚至可看作是一部新的创作，也是中外翻译史上的一个创举。
   #+end_example

** 一个坏的翻译的例子
   #+begin_example
   side effect翻译成边界效应。shell programming翻译成外壳编程。
   #+end_example
* 其他东西
  翻译的书会便宜一些
* 一些误区
  * 英文版的书籍看不懂
    1) 我英语不好，平时英语考试分数很低
    2) 翻译的书都看不懂，更别说原版的了
  * 影印版的质量很差
  * 国内的书籍更适合国情
  * 国内的书籍全部都是垃圾
  * 一本书出了这种多版一定是好书
  * 这是“十*五”规划教材，应该是好书
  * 这是专家主编的一定是好书
